project:
  type: website

website:
  title: "Eli Daniels"
  site-url: https://eli-daniels-data.com
  description: "This is Eli Daniels' website - it includes a portfolio, blog and CV"
  navbar:
    left: 
      - href: index.qmd
      - text: "Posts"
        href: posts.qmd
      #- href: about.qmd
      - icon: github
        href: https://github.com/EliDaniel5
      - icon: linkedin
        href: https://www.linkedin.com/in/eli-daniels011/


format:
  html:
    theme:
      light: [cosmo, theme-light.scss]
      #dark: [cosmo, theme-dark.scss]
    toc: true

editor: visual

